version: ~> 1.0

import:
  - silverstripe/silverstripe-travis-shared:config/provision/self.yml

jobs:
  fast_finish: true
  include:
    - php: 7.4
      env:
        - PHPUNIT_TEST=1
        - COMPOSER_INSTALL_ARG=--prefer-lowest
    - php: 8.0
      env:
        - PHPUNIT_TEST=1
        - PHPCS_TEST=1
    - php: 8.1
      env:
        - PHPUNIT_TEST=1
